import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Lato } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";

const latoFont = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${latoFont.className} antialiased w-screen h-screen flex flex-col`}
      >
        <header>
          <nav>
            <NavBar />
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
